#!/bin/bash

echo "Checking for gdtoolkit"
(type gdformat > /dev/null 2>&1 || pip install gdtoolkit || echo "Can't install gdtoolkit. Try to install it manually!" && exit 1)
echo "Gdtoolkit ready!"

echo "Preparing pre-commit hook"
cp scripts/pre-commit .git/hooks/pre-commit
chmod +x .git/hooks/pre-commit
echo "Pre-commit hook ready"
